//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boardgames
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<short> MinPlayers { get; set; }
        public Nullable<short> MaxPlayers { get; set; }
        public Nullable<short> MinAge { get; set; }
        public Nullable<short> GameTime { get; set; }
        public string GameWorld { get; set; }
        public string Category { get; set; }
        public string Language { get; set; }
        public string Publisher { get; set; }
        public string Author { get; set; }
        public Nullable<short> Year { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<short> FastTags { get; set; }
        public Nullable<bool> Extension { get; set; }
        public string Family { get; set; }
        public Nullable<short> ExtensionNumber { get; set; }
        public string Rules { get; set; }
        public string Keywords { get; set; }
        public byte[] Cover { get; set; }
        public byte[] Img1 { get; set; }
        public byte[] Img2 { get; set; }
        public byte[] Img3 { get; set; }
        public string MaterialPath { get; set; }
        public string URL { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<short> MyRating { get; set; }
        public Nullable<short> Count { get; set; }
        public Nullable<short> Available { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<bool> Excluded { get; set; }
    }
}
