//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string AuthorName { get; set; }
        public string AuthorSurname { get; set; }
        public string ISBN { get; set; }
        public string Illustrator { get; set; }
        public string Translator { get; set; }
        public string Language { get; set; }
        public string Publisher { get; set; }
        public string Edition { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<short> Pages { get; set; }
        public string MainCharacter { get; set; }
        public string URL { get; set; }
        public string Note { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Content { get; set; }
        public string OrigName { get; set; }
        public string OrigLanguage { get; set; }
        public Nullable<short> OrigYear { get; set; }
        public string Genre { get; set; }
        public string SubGenre { get; set; }
        public string Series { get; set; }
        public Nullable<long> SeriesNum { get; set; }
        public string Keywords { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<short> MyRating { get; set; }
        public Nullable<bool> Readed { get; set; }
        public Nullable<short> Count { get; set; }
        public Nullable<short> Available { get; set; }
        public string Type { get; set; }
        public string Bookbinding { get; set; }
        public byte[] Cover { get; set; }
        public Nullable<int> FastTags { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string EbookPath { get; set; }
        public string EbookType { get; set; }
        public Nullable<short> Publication { get; set; }
        public Nullable<bool> Excluded { get; set; }
    }
}
