//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowing
    {
        public System.Guid Id { get; set; }
        public string type { get; set; }
        public Nullable<System.Guid> item { get; set; }
        public Nullable<System.Guid> person { get; set; }
        public Nullable<System.DateTime> from { get; set; }
        public Nullable<System.DateTime> to { get; set; }
        public Nullable<bool> returned { get; set; }
    }
}
