//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Nick { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
        public string WWW { get; set; }
        public string IM { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Tags { get; set; }
        public Nullable<long> FastTags { get; set; }
        public string Partner { get; set; }
        public string Childs { get; set; }
        public string Parrents { get; set; }
        public byte[] Avatar { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public string CMobile { get; set; }
        public string CPhone { get; set; }
        public string CMail { get; set; }
        public string CWWW { get; set; }
        public string CStreet { get; set; }
        public string CCity { get; set; }
        public string CRegion { get; set; }
        public string CCountry { get; set; }
        public string CPostCode { get; set; }
        public string CICO { get; set; }
        public string CDIC { get; set; }
        public string sex { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> update { get; set; }
    }
}
