//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Subcategory { get; set; }
        public string Keywords { get; set; }
        public string Note { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string PlayerAge { get; set; }
        public Nullable<short> MinPlayers { get; set; }
        public Nullable<short> MaxPlayers { get; set; }
        public Nullable<short> Duration { get; set; }
        public Nullable<short> DurationPreparation { get; set; }
        public string Things { get; set; }
        public string URL { get; set; }
        public string Rules { get; set; }
        public string Preparation { get; set; }
        public string Environment { get; set; }
        public string Files { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<short> MyRating { get; set; }
        public Nullable<short> FastTags { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<bool> Excluded { get; set; }
    }
}
