//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lending
    {
        public System.Guid ID { get; set; }
        public string ItemType { get; set; }
        public Nullable<System.Guid> ItemID { get; set; }
        public Nullable<short> ItemNum { get; set; }
        public string ItemInvNum { get; set; }
        public Nullable<System.Guid> PersonID { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<short> Status { get; set; }
        public string Note { get; set; }
        public Nullable<short> FastTags { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
