//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Subcategory { get; set; }
        public string Keywords { get; set; }
        public string Note { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<short> MyRating { get; set; }
        public Nullable<short> FastTags { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Version { get; set; }
        public string Files { get; set; }
        public string Folder { get; set; }
        public string Type { get; set; }
        public string ObjectNum { get; set; }
        public string Language { get; set; }
        public Nullable<System.Guid> Parrent { get; set; }
        public string Customer { get; set; }
        public string Development { get; set; }
    }
}
