//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string OrigName { get; set; }
        public string MediaType { get; set; }
        public Nullable<short> Rating { get; set; }
        public string Genre { get; set; }
        public string Audio { get; set; }
        public string Subtitles { get; set; }
        public Nullable<short> Length { get; set; }
        public Nullable<short> Year { get; set; }
        public string Country { get; set; }
        public string Director { get; set; }
        public string Producer { get; set; }
        public string MajorRole { get; set; }
        public string Publishing { get; set; }
        public string Theme { get; set; }
        public string Screenplay { get; set; }
        public string Music { get; set; }
        public string Camera { get; set; }
        public string Note { get; set; }
        public string Format { get; set; }
        public Nullable<bool> Viewed { get; set; }
        public string Description { get; set; }
        public string InventoryNumber { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> AcquisitionDate { get; set; }
        public string Location { get; set; }
        public string FilePath { get; set; }
        public byte[] Cover { get; set; }
        public Nullable<System.DateTime> update { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
    }
}
